### ISSUE TITLE
Vehicle spawner defaults with permissions on relog

### ISSUE THREAD

**Issue by MrSchwepppes** [ChonkyBadger/Vehicle-Spawner#3]
I had a few server members of mine saying that every time they relogged, they were met with the menu only displaying the first category no matter their permissions. I've been able to personally verify.

**Comment by ChonkyBadger** [comment]
> I had a few server members of mine saying that every time they relogged, they were met with the menu only displaying the first category no matter their permissions. I've been able to personally verify.

Hi. So with how the permissions are done, at a certain point, it goes through all the different ace perms for each category by taking it from the config, checks which ones they have and takes those categories and puts it in a list to send to the client. This means that there is no way that only the first category would appear unless that is the only one they have permissions for.

**Comment by MrSchwepppes** [comment]
Turns out it just makes all of the categories disappear, could this be an incompatibility with discord ace permissions scripting?

**Comment by Calumjn98** [comment]
mine does the exact same thing

**Comment by ChonkyBadger** [comment]
Fix coming later this week. I've put it off a while.
