### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Cjneilson12** [ChonkyBadger/Vehicle-Spawner#4]
Hello, when I try start this I am greeted by a long error in my console and then at the start of my config.json is adds a `+`

![2022-08-12 11_21_37-Window](https://user-images.githubusercontent.com/96008403/184335496-fb7b44cb-a56f-4193-880d-3626dcc636fd.png)

**Comment by ChonkyBadger** [comment]
This indicates that you have somewhere in one of the json files messed up the Jason.
